import type { Metadata } from "next";
import '../../public/css/style.css'
import Footer from "./Footer/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
